name: Sync Fork

on:
  schedule:
    - cron: '0 3 * * *' # Every day at 3 AM UTC
  workflow_dispatch: # Optional: allows you to run it manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add upstream repo
        run: |
          git remote add upstream https://github.com/Balakrishna625/Terraform-Training.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
